"""new fields in user model

Revision ID: 90378c3e5f96
Revises: 542dacee36d2
Create Date: 2023-11-15 09:29:59.620350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90378c3e5f96'
down_revision = '542dacee36d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###